version: '3.4'

services:
  standalone:
    container_name: standalone
    image: nginx
    networks:
      - mandarin
    ports:
    - "8080:80"
    volumes:
    - "./css:/usr/share/nginx/html/css"
    - "./data:/usr/share/nginx/html/data"
    - "./js:/usr/share/nginx/html/js"
    - "./vizs:/usr/share/nginx/html/vizs"

networks:
  mandarin:
